### ISSUE TITLE
Vorticity Divergence Jupyter notebook does not work 

### ISSUE THREAD

**Issue by winash12** [evans36/miscellany#1]
I am trying to run this notebook - https://github.com/evans36/miscellany/blob/main/Vorticity%20and%20Divergence%20Inversion.ipynb

and I encounter an error with the MetPy calc function - vorticity - it takes 4 arguments according to my version of MetPy - u, v and dx and dy but your code seems to take only 2. What version of MetPy are you using may I know ?

**Comment by clarkevanswx** [comment]
Hi, we have MetPy v1.2 installed on the machine on which this notebook was derived. The required arguments appear to be the same between v1.2 and the current v1.5:

https://unidata.github.io/MetPy/v1.2/api/generated/metpy.calc.vorticity.html
https://unidata.github.io/MetPy/latest/api/generated/metpy.calc.vorticity.html

**Comment by winash12** [comment]
@evans36 Thanks for your prompt response I have referenced this issue on the MetPy tracker - https://github.com/Unidata/MetPy/issues/3152

**Comment by winash12** [comment]
@evans36 It was a version mismatch. I had several old versions of MetPy in my dist. Now working fine ! Thanks for your response again.
